<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Catalog\ViewModel\Product\Listing\PreparePostData;
use Magento\Framework\App\ActionInterface;

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $isWeightedRandom = (int) $block->getRotation()->isWeightedRandom($block->getProductListType());
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = true;
            $templateType = null;
            $description = false;
            $showQty = $canItemsAddToCart;
        }
        break;

    case 'related':
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $isWeightedRandom = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = true;
            $showQty = true;
            $templateType = null;
            $description = false;
            $showQty = $canItemsAddToCart;
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $isWeightedRandom = (int) $block->getRotation()->isWeightedRandom($block->getProductListType());

            $showAddTo = false;
            $showCart = true;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = true;
            $showQty = $canItemsAddToCart;
        }
        break;

    case 'upsell':
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;
            $isWeightedRandom = 0;

            $showAddTo = true;
            $showCart = true;
            $showQty = true;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = true;
            $showQty = $canItemsAddToCart;
        }
        break;

    default:
        $exist = null;
}
$_item = null;
?>

<?php if ($exist): ?>

    <div class="block <?= $block->escapeHtmlAttr($class) ?>"
         data-mage-init='<?= $type == "related" ? '{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' : '{"upsellProducts":{}}' ?>'
         data-limit="<?= $block->escapeHtmlAttr($limit) ?>"
         data-shuffle="<?= $shuffle ?>"
         data-shuffle-weighted="<?= $isWeightedRandom ?>">

        <div class="block-title title">
            <strong id="block-<?= $block->escapeHtmlAttr($class) ?>-heading" role="heading"
                    aria-level="2"><?= $block->escapeHtml($title) ?></strong>
        </div>

        <div class="block-content content" aria-labelledby="block-<?= $block->escapeHtmlAttr($class) ?>-heading">
            <div class="products wrapper grid products-grid products-<?= $block->escapeHtmlAttr($type) ?>">
                <ol class="products list items product-items">
                    <?php foreach ($items as $_item): ?>
                        <?php $available = ''; ?>
                        <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                            <?php if (!$_item->getRequiredOptions()): ?>
                                <?php $available = 'related-available'; ?>
                            <?php endif; ?>
                        <?php endif; ?>
                        <li class="item product product-item"
                            id="product-item_<?= $_item->getId() ?>"
                            <?= $type == 'related' || $type == 'upsell' ? 'data-shuffle-group="' . $block->escapeHtmlAttr($_item->getPriority()) . '"' : '' ?>>
                            <?= $secureRenderer->renderStyleAsTag('display:none;', 'li#product-item_' . $_item->getId()) ?>
                            <div class="product-item-info <?= $available ?>">
                                <?= '<!-- ' . $image . '-->' ?>
                                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                   class="product photo product-item-photo">
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </a>
                                <div class="product details product-item-details">
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link"
                                           title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                           href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>">
                                            <?= $block->escapeHtml($_item->getName()) ?>
                                        </a>
                                    </strong>

                                    <?= $block->getProductPrice($_item) ?>

                                    <?php if ($templateType): ?>
                                        <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>


                                    <?php if ($showAddTo || $showCart): ?>
                                        <div class="product actions product-item-actions">
                                            <?php if ($showCart): ?>
                                                <div class="actions-primary">
                                                    <?php if ($_item->isSaleable()): ?>
                                                        <?php if (!$_item->getTypeInstance()->isPossibleBuyFromList($_item)): ?>
                                                            <button class="action tocart primary"
                                                                    data-mage-init='{"redirectUrl":{"url":"<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}'
                                                                    type="button"
                                                                    title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                            </button>
                                                        <?php else: ?>
                                                            <?php
                                                            $viewModel = $block->getViewModel();
                                                            $postArray = $viewModel->getPostData($block->escapeUrl($block->getAddToCartUrl($_item)), ['product' => $_item->getEntityId()]);
                                                            $value = $postArray['data'][ActionInterface::PARAM_NAME_URL_ENCODED];
                                                            ?>
                                                            <form data-role="tocart-form"
                                                                  data-product-sku="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                                                                  action="<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"
                                                                  method="post">
                                                                <input type="hidden" name="product"
                                                                       value="<?= (int)$_item->getEntityId() ?>">
                                                                <input type="hidden"
                                                                       name="<?= ActionInterface::PARAM_NAME_URL_ENCODED ?>"
                                                                       value="<?= $value ?>">
                                                                <?= $block->getBlockHtml('formkey') ?>

                                                                 <?php if ($showQty): ?>
                                                                        <div class="field qty">
                                                                            <label class="label" for="qty_<?= $_item->getId() ?>">
                                                                                <span><?= __('Qty') ?></span>
                                                                            </label>
                                                                            <input type="number"
                                                                                name="qty"
                                                                                id="qty_<?= $_item->getId() ?>"
                                                                                value="1"
                                                                                min="1"
                                                                                class="input-text qty"
                                                                                data-role="cart-item-qty"/>
                                                                        </div>
                                                                <?php endif; ?>
                                                                <button type="submit"
                                                                        title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                                        class="action tocart primary">
                                                                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                </button>
                                                            </form>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>

                                            <?php if ($showAddTo): ?>
                                                <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                        <?= $addToBlock->setProduct($_item)->getChildHtml() ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ol>
            </div>
        </div>
    </div>

    <?php if (!$block->isRedirectToCartEnabled() && $_item): ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $block->escapeJs($_item->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif; ?>

<?php endif; ?>
